esphome:
  name: test-esp32c6-1
  friendly_name: Test ESP32C6 1

esp32:
  #esp32-c6 Fire Beetle v1.2
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    log_level: NONE
    sdkconfig_options:
      CONFIG_OPENTHREAD_LOG_LEVEL_DYNAMIC: "n"
      CONFIG_OPENTHREAD_LOG_LEVEL_NONE: "y"

logger:
  level: DEBUG

network:
  enable_ipv6: true

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key
