esphome:
  name: test-esp32c6-4
  friendly_name: Test ESP32C6 4
  on_boot:
    priority: -100
    then:
      - script.execute: wait_for_esphome_prevent_sleep_value

esp32:
  #esp32-c6 Fire Beetle v1.2
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    log_level: INFO

logger:
  level: DEBUG
  hardware_uart: UART0 # monitor via UART pins

network:
  enable_ipv6: true

openthread:
  device_type: mtd
#  force_dataset: true
  tlv: !secret openthread_tlv_wed
  output_power: 0
  on_connect:
      then:
      - logger.log: "openthread connected"
  on_disconnect:
      then:
      - logger.log: "openthread disconnected"

ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

deep_sleep:
  id: deep_sleep_1
  run_duration: 1min
  sleep_duration: 1min

# used to determine if hardware reboots are occuring
sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor_id
    type: seconds
    update_interval: 60sec

binary_sensor:
  - platform: homeassistant
    name: "Input Boolean Prevent Sleep Sensor"
    entity_id: input_boolean.esphome_prevent_sleep
    id: ESPHome_prevent_sleep_sensor
    trigger_on_initial_state: true
    internal: true
    # transition of input_boolean.esphome_prevent_sleep during awake
    on_state:
      then:
      - if:
          condition:
            binary_sensor.is_on: ESPHome_prevent_sleep_sensor
          then:
            - logger.log: "input_boolean.esphome_prevent_sleep ON, prevent deep sleep"
            - deep_sleep.prevent: deep_sleep_1
          else:
            - logger.log: "input_boolean.esphome_prevent_sleep OFF, enter deep sleep"
            - deep_sleep.enter: deep_sleep_1

# wakeup check of input_boolean.esphome_prevent_sleep
script:
  - id: wait_for_esphome_prevent_sleep_value
    mode: queued
    then:
      - wait_until:
          condition:
            api.connected: {}
      - component.update: uptime_sensor_id
      - wait_until:
          condition:
            lambda: return id(ESPHome_prevent_sleep_sensor).has_state();
      - if:
          condition:
            binary_sensor.is_on: ESPHome_prevent_sleep_sensor
          then:
            - logger.log: "input_boolean.esphome_prevent_sleep ON, prevent deep sleep"
            - deep_sleep.prevent: deep_sleep_1
          else:
            - logger.log: "input_boolean.esphome_prevent_sleep OFF, enter deep sleep"
            - deep_sleep.enter: deep_sleep_1

    