external_components:
  # [power_management] new component that enables power management for esp_idf
  - source: github://pr#12325
    components: [power_management]
    refresh: 1h
  # [openthread] Provide action to control radio on/off when poll_period > 0
  - source: github://pr#11766
    components: [openthread]
    refresh: 1h

esphome:
  name: test-esp32c6-1
  friendly_name: Test ESP32C6 1

esp32:
  #esp32-c6 Fire Beetle v1.2
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    log_level: NONE
    sdkconfig_options:
      CONFIG_OPENTHREAD_LOG_LEVEL_DYNAMIC: "n"
      CONFIG_OPENTHREAD_LOG_LEVEL_NONE: "y"

logger:
  level: NONE

power_management:
  enable_light_sleep: true
  power_down_flash: true
  power_down_peripherals: true

network:
  enable_ipv6: true

openthread:
  device_type: mtd
  tlv: !secret openthread_tlv
  poll_period: 10sec

api:
  encryption:
    key: !secret api_encryption_key

switch:
  - platform: template
    name: "Radio Always On"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      then:
        - logger.log: "Radio Always On"
        - openthread.radio: true
    turn_off_action:
      then:
        - logger.log: "Radio Off When Idle"
        - openthread.radio: false
