external_components:
  # [power_management] new component that enables power management for esp_idf
  - source: github://pr#12325
    components: [power_management]
    refresh: 1h

esphome:
  name: test-esp32-1
  friendly_name: Test ESP32 1

esp32:
  variant: esp32
  framework:
    type: esp-idf
    log_level: INFO
    advanced:
      minimum_chip_revision: "3.1"

logger:
  level: NONE

power_management:
  enable_light_sleep: true
  power_down_flash: true
  power_down_peripherals: false

network:
  enable_ipv6: true

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key
